In [85]:
import pandas as pd
import numpy as np


from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [35]:
Tcredits = pd.read_csv("../datasets/TMDB/tmdb_5000_credits.csv")

In [36]:
Tmovies = pd.read_csv("../datasets/TMDB/tmdb_5000_movies.csv")

In [51]:
Tmovies
Tmovies_1 = Tmovies[['genres','id','keywords','title','overview','popularity','production_companies','release_date','tagline','vote_average','vote_count']]
Tmovies_1

,genres,id,keywords,title,overview,popularity,production_companies,release_date,tagline,vote_average,vote_count
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,Enter the World of Pandora.,7.2,11800
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,"At the end of the world, the adventure begins.",6.9,4500
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,A Plan No One Escapes,6.3,4466
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,The Legend Ends,7.6,9106
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,"Lost in our world, found in another.",6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...
4798,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",1992-09-04,"He didn't come looking for trouble, but troubl...",6.6,238
4799,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",72766,[],Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],2011-12-26,A newlywed couple's honeymoon is upended by th...,5.9,5
4800,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",2013-10-13,NaN,7.0,6
4801,[],126186,[],Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],2012-05-03,A New Yorker in Shanghai,5.7,7
4802,"[{""id"": 99, ""name"": ""Documentary""}]",25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",2005-08-05,NaN,6.3,16

In [52]:
Tcredits

,id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [39]:
# the id column names are different in both datasets. 
Tcredits = Tcredits.rename(columns={"movie_id":"id"})

In [54]:
#combine to single dataframe
Tmovies_1.merge(Tcredits,on="id")

,genres,id,keywords,title_x,overview,popularity,production_companies,release_date,tagline,vote_average,vote_count,title_y,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,Enter the World of Pandora.,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,"At the end of the world, the adventure begins.",6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,A Plan No One Escapes,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,The Legend Ends,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,"Lost in our world, found in another.",6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",1992-09-04,"He didn't come looking for trouble, but troubl...",6.6,238,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",72766,[],Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],2011-12-26,A newlywed couple's honeymoon is upended by th...,5.9,5,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",2013-10-13,NaN,7.0,6,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,[],126186,[],Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],2012-05-03,A New Yorker in Shanghai,5.7,7,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,"[{""id"": 99, ""name"": ""Documentary""}]",25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",2005-08-05,NaN,6.3,16,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [55]:
Tmovies_1.isnull().sum()

genres                    0
id                        0
keywords                  0
title                     0
overview                  3
popularity                0
production_companies      0
release_date              1
tagline                 844
vote_average              0
vote_count                0
dtype: int64

In [81]:
Tmovies_1 = Tmovies_1.fillna("")
Tmovies_1.isnull().sum()

genres                  0
id                      0
keywords                0
title                   0
overview                0
popularity              0
production_companies    0
release_date            0
tagline                 0
vote_average            0
vote_count              0
dtype: int64

In [82]:
movies.duplicated().sum()
Tmovies_1['overview']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: overview, Length: 4803, dtype: object

In [105]:
vectorizer = TfidfVectorizer(stop_words='english')
matrix = vectorizer.fit_transform(Tmovies_1['overview'])

matrix
# it is mxn matrix with m equal to the total rows of  dataset. 
# n is total no of different words used in overview column
# now if given a row or title we need to find other rows with similar data in the matrix

<4803x20978 sparse matrix of type '<class 'numpy.float64'>'
	with 125840 stored elements in Compressed Sparse Row format>

In [196]:
sim_score = linear_kernel(matrix, matrix)
# it finds the similarity with all other rows in matrix and returns a list

In [197]:
print(sim_score[0])
print(sim_score[1])
print(sim_score[2])
# each row has similarity value of 1 with itself

[1. 0. 0. ... 0. 0. 0.]
[0.         1.         0.         ... 0.02160533 0.         0.        ]
[0.         0.         1.         ... 0.01488159 0.         0.        ]

In [198]:
indexMap = pd.Series(Tmovies_1.index, index=Tmovies_1['title'])
indexMap.duplicated().sum()

0

In [205]:
indexMap
sim_indices = np.argsort(sim_score[0])[-11:]
a
#https://stackoverflow.com/questions/7851077/how-to-return-index-of-a-sorted-list

array([2628,  775,  847,  311, 1610,  529, 1341,  634, 2130, 3604,    0])

In [201]:
a = list(enumerate(sim_score[0])) 
b = sorted(a, key=lambda x: x[1], reverse=True)
b

[(0, 1.0),
 (3604, 0.18681001056212054),
 (2130, 0.17015105119162663),
 (634, 0.13230696630317224),
 (1341, 0.12393264590871879),
 (529, 0.12248959164893028),
 (1610, 0.10469903037615635),
 (311, 0.10091388184065117),
 (847, 0.09799623121705058),
 (775, 0.09447938436890335),
 (2628, 0.09313854469530522),
 (942, 0.0924514241892011),
 (1033, 0.08753936247200367),
 (2767, 0.0818486532344246),
 (570, 0.08077097525490028),
 (1213, 0.07871095243967652),
 (2967, 0.07678602071424366),
 (2875, 0.07644276205946182),
 (3070, 0.07624478735120209),
 (36, 0.07454624070840556),
 (1013, 0.0744420990745722),
 (4211, 0.07329392043813658),
 (3724, 0.07307988854131138),
 (1274, 0.07230185082235971),
 (1784, 0.07176095764781792),
 (3970, 0.07138284265967441),
 (2578, 0.07063238531821642),
 (1959, 0.07011201811048635),
 (281, 0.0699103290579774),
 (150, 0.06865963374809526),
 (1345, 0.0676133596560152),
 (312, 0.0671326953894372),
 (3458, 0.06589361955408915),
 (151, 0.06547158879247776),
 (2614, 0.06516707289778173),
 (972, 0.06427195078268814),
 (83, 0.06410697319741618),
 (3624, 0.06357675423012704),
 (3948, 0.06244582273835789),
 (823, 0.062200311694291466),
 (4039, 0.062052758253273055),
 (31, 0.06153392877569968),
 (3302, 0.061331291913560584),
 (45, 0.0611498614502933),
 (1482, 0.060706584869772276),
 (614, 0.06031174636398869),
 (404, 0.06009956529690274),
 (1843, 0.05935429963132434),
 (1914, 0.05900310903751847),
 (1633, 0.05869012971351403),
 (4754, 0.05849888278827216),
 (2193, 0.05847143493785078),
 (2008, 0.05805534705005179),
 (2684, 0.05786944801447969),
 (74, 0.057815482699066105),
 (2636, 0.05777641297846376),
 (174, 0.05755334169283926),
 (2990, 0.05725948083864203),
 (3710, 0.05711238349407722),
 (68, 0.056041553338482666),
 (2509, 0.05573895450377702),
 (3336, 0.05564924343698746),
 (3618, 0.05564756737076546),
 (2218, 0.05562560969540324),
 (1199, 0.05535816701864523),
 (2616, 0.05515257500183098),
 (985, 0.05495774887724781),
 (1513, 0.05403044282445301),
 (2626, 0.05309850088790117),
 (582, 0.053085194509317916),
 (369, 0.05300098924470275),
 (3493, 0.052965709225465715),
 (3695, 0.05276635160788556),
 (1547, 0.052599182905908835),
 (2424, 0.05173815283195214),
 (1318, 0.051728671347657816),
 (1644, 0.05141956266453764),
 (1301, 0.051251368394485027),
 (236, 0.05116544628709476),
 (1653, 0.05086213601414275),
 (1438, 0.05079572404236148),
 (894, 0.05061767967036855),
 (2964, 0.05037652971915796),
 (1528, 0.04997009937866124),
 (2781, 0.04989132839347539),
 (1158, 0.04963769924981252),
 (1275, 0.04963751001546288),
 (4328, 0.049224401119105185),
 (3197, 0.04860196901398581),
 (951, 0.048520361915749384),
 (1434, 0.04836703542760082),
 (3297, 0.04818667505728802),
 (646, 0.048169935318009616),
 (1467, 0.04804187516535899),
 (1649, 0.0480401657334354),
 (3419, 0.04791854390538248),
 (1796, 0.047809169029929266),
 (568, 0.047807053061429024),
 (2327, 0.04759406514247867),
 (3087, 0.04746583870930876),
 (1782, 0.0473311900342835),
 (1198, 0.047213144492645784),
 (27, 0.04705452709989043),
 (199, 0.046958011081237344),
 (107, 0.046930282667708836),
 (4263, 0.046599496347680056),
 (475, 0.04644653205228709),
 (4176, 0.04634999158591747),
 (1163, 0.045897784249609476),
 (2370, 0.04574211458587508),
 (617, 0.04571627911391384),
 (3306, 0.045407801494765865),
 (2016, 0.045307972142762915),
 (507, 0.04517744711375713),
 (3747, 0.04506565037945454),
 (4042, 0.045050735177289705),
 (1016, 0.044987086409385944),
 (483, 0.04494674043593565),
 (140, 0.044794888096614936),
 (373, 0.04443314049472812),
 (2645, 0.044368758170098485),
 (4591, 0.04387537325317616),
 (2543, 0.04372787798472926),
 (1802, 0.04324274488873942),
 (1034, 0.04316538572388099),
 (539, 0.04313550433652452),
 (3068, 0.04291599244094623),
 (626, 0.04258263725533966),
 (1020, 0.042458480440989495),
 (4796, 0.04217579844522391),
 (4187, 0.04214095695597864),
 (3312, 0.04190519272842585),
 (1326, 0.041788873110911604),
 (3396, 0.0417542919126693),
 (2951, 0.041749166685001234),
 (557, 0.04162548311884122),
 (2226, 0.04151452221861138),
 (513, 0.04129006722051004),
 (1735, 0.04124230980025596),
 (2721, 0.04098563118983616),
 (495, 0.04089512610792396),
 (1491, 0.040833452755027914),
 (835, 0.040731354394342785),
 (1763, 0.04061420438414692),
 (4301, 0.040335180890000835),
 (3105, 0.0402705738129889),
 (1817, 0.040125892395583285),
 (2808, 0.0400904928276533),
 (1067, 0.04005329481368889),
 (1967, 0.03962840755749321),
 (4649, 0.03940358965279206),
 (1840, 0.039357869936335645),
 (1172, 0.03929316003355795),
 (466, 0.03923759935588713),
 (487, 0.03920469830669222),
 (1188, 0.03895819451443086),
 (149, 0.038675087190328424),
 (2878, 0.038559152163274255),
 (2194, 0.0385241952608891),
 (2920, 0.03833641714829675),
 (3789, 0.03816489410636917),
 (1042, 0.038048907172140635),
 (1106, 0.03800451670004117),
 (3498, 0.03795184100651576),
 (1402, 0.03790480009587174),
 (581, 0.037864564058534084),
 (2874, 0.03781943313578341),
 (3656, 0.037760528969713957),
 (1118, 0.03767714334981816),
 (7, 0.03758069690343087),
 (1414, 0.03716581949951029),
 (3172, 0.03691280790451268),
 (4347, 0.0368493441674492),
 (3098, 0.0367863454543343),
 (4637, 0.03673287775803145),
 (365, 0.03657882540123637),
 (3833, 0.03654875408485645),
 (637, 0.036434035425775384),
 (4119, 0.03638186872457356),
 (3104, 0.036226794144243915),
 (535, 0.036165962378131994),
 (4617, 0.036126751214878565),
 (1272, 0.036055131200168615),
 (4313, 0.03599971365217785),
 (148, 0.03581968276882978),
 (4074, 0.03580404576842152),
 (1279, 0.03573976501228619),
 (3191, 0.03547052960839848),
 (946, 0.03534592628030857),
 (871, 0.03529438406744968),
 (1068, 0.03506529448434587),
 (2382, 0.035039766374401385),
 (26, 0.0349695829781853),
 (3626, 0.034903584226251866),
 (4481, 0.034699859197325496),
 (2724, 0.03461257499568083),
 (467, 0.03440907786854097),
 (47, 0.03398446515527808),
 (91, 0.03395471892695029),
 (4376, 0.03393758202818358),
 (1246, 0.03376276414250318),
 (1463, 0.03372758850570014),
 (1004, 0.0336693925901678),
 (549, 0.03363868348522841),
 (2797, 0.03359348253604296),
 (1271, 0.033575992214020786),
 (2011, 0.03342169244941258),
 (4045, 0.03339721139586969),
 (2529, 0.033142722330109044),
 (2051, 0.033116205910928384),
 (134, 0.03310689282980267),
 (313, 0.03303373167406416),
 (2863, 0.03302586185660089),
 (1201, 0.0329987877401627),
 (1920, 0.03293678802283698),
 (2132, 0.03278958534842177),
 (275, 0.03265905578071967),
 (473, 0.03260911551788165),
 (1665, 0.03218108871664175),
 (692, 0.03206035530418174),
 (2314, 0.03203008768098077),
 (1449, 0.031603530553910936),
 (3643, 0.03154377817366802),
 (2726, 0.03134358716843709),
 (4038, 0.03128661505317486),
 (3004, 0.03128528792043585),
 (1117, 0.031107476698567223),
 (2876, 0.031067119121991872),
 (3501, 0.03087187839100913),
 (4106, 0.030774473551041705),
 (3221, 0.03075822927022944),
 (1594, 0.030386416922999752),
 (1285, 0.03036209219001393),
 (5, 0.0303525438443129),
 (875, 0.03005701752433769),
 (2142, 0.02996375690154135),
 (3516, 0.029891982140903245),
 (1412, 0.029884614452859042),
 (1175, 0.02973168980278747),
 (454, 0.029683715377209593),
 (2583, 0.02965161324862762),
 (3018, 0.02947279583435352),
 (1471, 0.029463075510120375),
 (3249, 0.029266621069802372),
 (3908, 0.029248514780548202),
 (1529, 0.02921575108946754),
 (3325, 0.029192938991687088),
 (4795, 0.02917497485824725),
 (785, 0.029161143906673063),
 (672, 0.02898697232295572),
 (632, 0.028956158569231883),
 (1741, 0.028933342249313505),
 (2109, 0.028929729786554375),
 (2408, 0.028848726957562583),
 (2250, 0.028840626418365788),
 (4630, 0.028837987506242144),
 (1753, 0.028751324287058094),
 (4629, 0.028479053573356675),
 (1377, 0.028296854563938535),
 (2599, 0.02826325400062851),
 (1834, 0.02826088997301317),
 (2403, 0.028086567967995232),
 (1957, 0.027948665606142814),
 (2541, 0.027908560674616632),
 (2735, 0.027788141171057656),
 (137, 0.02777434677489505),
 (430, 0.02776591216147135),
 (1012, 0.027749772923870607),
 (127, 0.027592023534189655),
 (3161, 0.02754524660748937),
 (2819, 0.027428165242064022),
 (787, 0.02718737836955115),
 (1278, 0.02713469542746391),
 (4288, 0.02685469995478871),
 (1053, 0.026853751668285675),
 (2048, 0.026785574757284006),
 (3570, 0.026601427883087024),
 (502, 0.02652851002563906),
 (3616, 0.026492460270229397),
 (2229, 0.02629065024263193),
 (1727, 0.0262794796325837),
 (488, 0.026279379704825537),
 (432, 0.02610015182727537),
 (1532, 0.025861343459711025),
 (2198, 0.025798769403854192),
 (2687, 0.02573267421247941),
 (3351, 0.025587474751260407),
 (1319, 0.02558541382563091),
 (3776, 0.025564919661210668),
 (1217, 0.025464897866913333),
 (139, 0.02539121798504248),
 (29, 0.02518543163480529),
 (2220, 0.025100104078272158),
 (3158, 0.025071670399411532),
 (2081, 0.02504317776409268),
 (3, 0.0249951158376727),
 (4057, 0.024792965189154147),
 (3944, 0.02473712195718909),
 (2024, 0.024583003277917754),
 (838, 0.024478629672101248),
 (4542, 0.024341171345442243),
 (1999, 0.02429690493576469),
 (1939, 0.024135694981649553),
 (3993, 0.024077848313706057),
 (3364, 0.024060334108131274),
 (2789, 0.02400435770044089),
 (2859, 0.0239449906730652),
 (3971, 0.023901897105924923),
 (3386, 0.023872647634995546),
 (342, 0.023794524481607675),
 (3931, 0.02376897988308547),
 (2664, 0.023732218892097),
 (184, 0.02370071251688892),
 (3439, 0.023686569110842024),
 (1678, 0.023521003941729183),
 (595, 0.02351076105310096),
 (854, 0.023475523398751485),
 (3294, 0.023447307693613986),
 (2646, 0.023404562093940616),
 (1912, 0.02330948190095684),
 (2644, 0.0232021479465548),
 (2812, 0.02313640541146506),
 (758, 0.023127346719994283),
 (3096, 0.023087829197559976),
 (2366, 0.02301281233812285),
 (4273, 0.02292179904644128),
 (782, 0.022840816889601396),
 (2496, 0.022756116215902657),
 (883, 0.022746472656163023),
 (901, 0.022719632312045223),
 (2936, 0.02262365650919966),
 (87, 0.02259280375204441),
 (3804, 0.022561480701048832),
 (420, 0.02255485290093571),
 (1606, 0.02253803364854206),
 (2258, 0.022480418343762458),
 (2658, 0.022393807603381787),
 (307, 0.022194367066117767),
 (899, 0.022182488221946496),
 (4654, 0.022128677082522277),
 (3556, 0.022120708735104487),
 (3195, 0.022108465619478632),
 (170, 0.021912013516845123),
 (3666, 0.02189332501993231),
 (1525, 0.021821934901589252),
 (1138, 0.021820117648756104),
 (43, 0.021794850562028286),
 (461, 0.02175762778252732),
 (270, 0.021470734434860243),
 (301, 0.021409585912668814),
 (2550, 0.021404013583064607),
 (1395, 0.021300198517184576),
 (3723, 0.021114829739962027),
 (588, 0.02073909884635409),
 (372, 0.020735936546165023),
 (213, 0.02068500525011147),
 (1672, 0.020557121474120765),
 (635, 0.020538966140854924),
 (3427, 0.020399923913560873),
 (131, 0.020353046942361785),
 (4323, 0.02034914521273585),
 (1302, 0.02027231706102384),
 (1531, 0.020127351686098915),
 (2358, 0.020116254774800262),
 (1822, 0.02004471408283495),
 (2482, 0.019986705572184422),
 (1365, 0.019976226768556468),
 (1506, 0.019883286963171664),
 (790, 0.019839130080640793),
 (794, 0.019798257418193084),
 (11, 0.01978766288618951),
 (228, 0.01975219800843654),
 (3657, 0.019733372952691522),
 (804, 0.01952746537374202),
 (2361, 0.01949859617495082),
 (1737, 0.01936420685934319),
 (999, 0.019326530028230562),
 (3534, 0.018958193342177382),
 (1986, 0.01893767436432008),
 (596, 0.01889911646725002),
 (2160, 0.01847121964498233),
 (3729, 0.01841724861902314),
 (1555, 0.018203994382523514),
 (456, 0.01809767197857577),
 (2197, 0.01806483004197202),
 (2147, 0.018032377738261135),
 (4653, 0.018011571246544605),
 (2704, 0.017907404858720218),
 (2066, 0.017495978774198232),
 (4007, 0.017307031272704654),
 (1473, 0.017249626611849433),
 (4550, 0.01724709107674135),
 (343, 0.017229086099229508),
 (3945, 0.01710998397219268),
 (4260, 0.0170225025692601),
 (1354, 0.016911046785727964),
 (412, 0.01687055268333849),
 (1298, 0.016811243676089355),
 (406, 0.016747487471142637),
 (1892, 0.016650624641737197),
 (4526, 0.016414248414835374),
 (153, 0.01634565620124889),
 (102, 0.016262565556291183),
 (1779, 0.01590219299088268),
 (277, 0.015892061702049615),
 (239, 0.015505465642114519),
 (222, 0.015357449216930663),
 (89, 0.01514863743720984),
 (2144, 0.015031029957481758),
 (2043, 0.014870571974014993),
 (206, 0.014858284268416457),
 (4679, 0.014764827633395181),
 (4326, 0.01406145101137881),
 (3505, 0.013975803745574934),
 (230, 0.013429784822891498),
 (2427, 0.01323375424429631),
 (3550, 0.012816584738869539),
 (599, 0.011305195818488966),
 (1, 0.0),
 (2, 0.0),
 (4, 0.0),
 (6, 0.0),
 (8, 0.0),
 (9, 0.0),
 (10, 0.0),
 (12, 0.0),
 (13, 0.0),
 (14, 0.0),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 0.0),
 (19, 0.0),
 (20, 0.0),
 (21, 0.0),
 (22, 0.0),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (28, 0.0),
 (30, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0),
 (42, 0.0),
 (44, 0.0),
 (46, 0.0),
 (48, 0.0),
 (49, 0.0),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.0),
 (55, 0.0),
 (56, 0.0),
 (57, 0.0),
 (58, 0.0),
 (59, 0.0),
 (60, 0.0),
 (61, 0.0),
 (62, 0.0),
 (63, 0.0),
 (64, 0.0),
 (65, 0.0),
 (66, 0.0),
 (67, 0.0),
 (69, 0.0),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (73, 0.0),
 (75, 0.0),
 (76, 0.0),
 (77, 0.0),
 (78, 0.0),
 (79, 0.0),
 (80, 0.0),
 (81, 0.0),
 (82, 0.0),
 (84, 0.0),
 (85, 0.0),
 (86, 0.0),
 (88, 0.0),
 (90, 0.0),
 (92, 0.0),
 (93, 0.0),
 (94, 0.0),
 (95, 0.0),
 (96, 0.0),
 (97, 0.0),
 (98, 0.0),
 (99, 0.0),
 (100, 0.0),
 (101, 0.0),
 (103, 0.0),
 (104, 0.0),
 (105, 0.0),
 (106, 0.0),
 (108, 0.0),
 (109, 0.0),
 (110, 0.0),
 (111, 0.0),
 (112, 0.0),
 (113, 0.0),
 (114, 0.0),
 (115, 0.0),
 (116, 0.0),
 (117, 0.0),
 (118, 0.0),
 (119, 0.0),
 (120, 0.0),
 (121, 0.0),
 (122, 0.0),
 (123, 0.0),
 (124, 0.0),
 (125, 0.0),
 (126, 0.0),
 (128, 0.0),
 (129, 0.0),
 (130, 0.0),
 (132, 0.0),
 (133, 0.0),
 (135, 0.0),
 (136, 0.0),
 (138, 0.0),
 (141, 0.0),
 (142, 0.0),
 (143, 0.0),
 (144, 0.0),
 (145, 0.0),
 (146, 0.0),
 (147, 0.0),
 (152, 0.0),
 (154, 0.0),
 (155, 0.0),
 (156, 0.0),
 (157, 0.0),
 (158, 0.0),
 (159, 0.0),
 (160, 0.0),
 (161, 0.0),
 (162, 0.0),
 (163, 0.0),
 (164, 0.0),
 (165, 0.0),
 (166, 0.0),
 (167, 0.0),
 (168, 0.0),
 (169, 0.0),
 (171, 0.0),
 (172, 0.0),
 (173, 0.0),
 (175, 0.0),
 (176, 0.0),
 (177, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.0),
 (181, 0.0),
 (182, 0.0),
 (183, 0.0),
 (185, 0.0),
 (186, 0.0),
 (187, 0.0),
 (188, 0.0),
 (189, 0.0),
 (190, 0.0),
 (191, 0.0),
 (192, 0.0),
 (193, 0.0),
 (194, 0.0),
 (195, 0.0),
 (196, 0.0),
 (197, 0.0),
 (198, 0.0),
 (200, 0.0),
 (201, 0.0),
 (202, 0.0),
 (203, 0.0),
 (204, 0.0),
 (205, 0.0),
 (207, 0.0),
 (208, 0.0),
 (209, 0.0),
 (210, 0.0),
 (211, 0.0),
 (212, 0.0),
 (214, 0.0),
 (215, 0.0),
 (216, 0.0),
 (217, 0.0),
 (218, 0.0),
 (219, 0.0),
 (220, 0.0),
 (221, 0.0),
 (223, 0.0),
 (224, 0.0),
 (225, 0.0),
 (226, 0.0),
 (227, 0.0),
 (229, 0.0),
 (231, 0.0),
 (232, 0.0),
 (233, 0.0),
 (234, 0.0),
 (235, 0.0),
 (237, 0.0),
 (238, 0.0),
 (240, 0.0),
 (241, 0.0),
 (242, 0.0),
 (243, 0.0),
 (244, 0.0),
 (245, 0.0),
 (246, 0.0),
 (247, 0.0),
 (248, 0.0),
 (249, 0.0),
 (250, 0.0),
 (251, 0.0),
 (252, 0.0),
 (253, 0.0),
 (254, 0.0),
 (255, 0.0),
 (256, 0.0),
 (257, 0.0),
 (258, 0.0),
 (259, 0.0),
 (260, 0.0),
 (261, 0.0),
 (262, 0.0),
 (263, 0.0),
 (264, 0.0),
 (265, 0.0),
 (266, 0.0),
 (267, 0.0),
 (268, 0.0),
 (269, 0.0),
 (271, 0.0),
 (272, 0.0),
 (273, 0.0),
 (274, 0.0),
 (276, 0.0),
 (278, 0.0),
 (279, 0.0),
 (280, 0.0),
 (282, 0.0),
 (283, 0.0),
 (284, 0.0),
 (285, 0.0),
 (286, 0.0),
 (287, 0.0),
 (288, 0.0),
 (289, 0.0),
 (290, 0.0),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0),
 (294, 0.0),
 (295, 0.0),
 (296, 0.0),
 (297, 0.0),
 (298, 0.0),
 (299, 0.0),
 (300, 0.0),
 (302, 0.0),
 (303, 0.0),
 (304, 0.0),
 (305, 0.0),
 (306, 0.0),
 (308, 0.0),
 (309, 0.0),
 (310, 0.0),
 (314, 0.0),
 (315, 0.0),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.0),
 (320, 0.0),
 (321, 0.0),
 (322, 0.0),
 (323, 0.0),
 (324, 0.0),
 (325, 0.0),
 (326, 0.0),
 (327, 0.0),
 (328, 0.0),
 (329, 0.0),
 (330, 0.0),
 (331, 0.0),
 (332, 0.0),
 (333, 0.0),
 (334, 0.0),
 (335, 0.0),
 (336, 0.0),
 (337, 0.0),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (344, 0.0),
 (345, 0.0),
 (346, 0.0),
 (347, 0.0),
 (348, 0.0),
 (349, 0.0),
 (350, 0.0),
 (351, 0.0),
 (352, 0.0),
 (353, 0.0),
 (354, 0.0),
 (355, 0.0),
 (356, 0.0),
 (357, 0.0),
 (358, 0.0),
 (359, 0.0),
 (360, 0.0),
 (361, 0.0),
 (362, 0.0),
 (363, 0.0),
 (364, 0.0),
 (366, 0.0),
 (367, 0.0),
 (368, 0.0),
 (370, 0.0),
 (371, 0.0),
 (374, 0.0),
 (375, 0.0),
 (376, 0.0),
 (377, 0.0),
 (378, 0.0),
 (379, 0.0),
 (380, 0.0),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0),
 (384, 0.0),
 (385, 0.0),
 (386, 0.0),
 (387, 0.0),
 (388, 0.0),
 (389, 0.0),
 (390, 0.0),
 (391, 0.0),
 (392, 0.0),
 (393, 0.0),
 (394, 0.0),
 (395, 0.0),
 (396, 0.0),
 (397, 0.0),
 (398, 0.0),
 (399, 0.0),
 (400, 0.0),
 (401, 0.0),
 (402, 0.0),
 (403, 0.0),
 (405, 0.0),
 (407, 0.0),
 (408, 0.0),
 (409, 0.0),
 (410, 0.0),
 (411, 0.0),
 (413, 0.0),
 (414, 0.0),
 (415, 0.0),
 (416, 0.0),
 (417, 0.0),
 (418, 0.0),
 (419, 0.0),
 (421, 0.0),
 (422, 0.0),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.0),
 (429, 0.0),
 (431, 0.0),
 (433, 0.0),
 (434, 0.0),
 (435, 0.0),
 (436, 0.0),
 (437, 0.0),
 (438, 0.0),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.0),
 (443, 0.0),
 (444, 0.0),
 (445, 0.0),
 (446, 0.0),
 (447, 0.0),
 (448, 0.0),
 (449, 0.0),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (453, 0.0),
 (455, 0.0),
 (457, 0.0),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (462, 0.0),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (468, 0.0),
 (469, 0.0),
 (470, 0.0),
 (471, 0.0),
 (472, 0.0),
 (474, 0.0),
 (476, 0.0),
 (477, 0.0),
 (478, 0.0),
 (479, 0.0),
 (480, 0.0),
 (481, 0.0),
 (482, 0.0),
 (484, 0.0),
 (485, 0.0),
 (486, 0.0),
 (489, 0.0),
 (490, 0.0),
 (491, 0.0),
 (492, 0.0),
 (493, 0.0),
 (494, 0.0),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0),
 (499, 0.0),
 (500, 0.0),
 (501, 0.0),
 (503, 0.0),
 (504, 0.0),
 (505, 0.0),
 (506, 0.0),
 (508, 0.0),
 (509, 0.0),
 (510, 0.0),
 (511, 0.0),
 (512, 0.0),
 (514, 0.0),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.0),
 (524, 0.0),
 (525, 0.0),
 (526, 0.0),
 (527, 0.0),
 (528, 0.0),
 (530, 0.0),
 (531, 0.0),
 (532, 0.0),
 (533, 0.0),
 (534, 0.0),
 (536, 0.0),
 (537, 0.0),
 (538, 0.0),
 (540, 0.0),
 (541, 0.0),
 (542, 0.0),
 (543, 0.0),
 (544, 0.0),
 (545, 0.0),
 (546, 0.0),
 (547, 0.0),
 (548, 0.0),
 (550, 0.0),
 (551, 0.0),
 (552, 0.0),
 (553, 0.0),
 (554, 0.0),
 (555, 0.0),
 (556, 0.0),
 (558, 0.0),
 (559, 0.0),
 (560, 0.0),
 (561, 0.0),
 (562, 0.0),
 (563, 0.0),
 (564, 0.0),
 (565, 0.0),
 (566, 0.0),
 (567, 0.0),
 (569, 0.0),
 (571, 0.0),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.0),
 (576, 0.0),
 (577, 0.0),
 (578, 0.0),
 (579, 0.0),
 (580, 0.0),
 (583, 0.0),
 (584, 0.0),
 (585, 0.0),
 (586, 0.0),
 (587, 0.0),
 (589, 0.0),
 (590, 0.0),
 (591, 0.0),
 (592, 0.0),
 (593, 0.0),
 (594, 0.0),
 (597, 0.0),
 (598, 0.0),
 (600, 0.0),
 (601, 0.0),
 (602, 0.0),
 (603, 0.0),
 (604, 0.0),
 (605, 0.0),
 (606, 0.0),
 (607, 0.0),
 (608, 0.0),
 (609, 0.0),
 (610, 0.0),
 (611, 0.0),
 (612, 0.0),
 (613, 0.0),
 (615, 0.0),
 (616, 0.0),
 (618, 0.0),
 (619, 0.0),
 (620, 0.0),
 (621, 0.0),
 (622, 0.0),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (627, 0.0),
 (628, 0.0),
 (629, 0.0),
 (630, 0.0),
 (631, 0.0),
 (633, 0.0),
 (636, 0.0),
 (638, 0.0),
 (639, 0.0),
 (640, 0.0),
 (641, 0.0),
 (642, 0.0),
 (643, 0.0),
 (644, 0.0),
 (645, 0.0),
 (647, 0.0),
 (648, 0.0),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.0),
 (653, 0.0),
 (654, 0.0),
 (655, 0.0),
 (656, 0.0),
 (657, 0.0),
 (658, 0.0),
 (659, 0.0),
 (660, 0.0),
 (661, 0.0),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0),
 (665, 0.0),
 (666, 0.0),
 (667, 0.0),
 (668, 0.0),
 (669, 0.0),
 (670, 0.0),
 (671, 0.0),
 (673, 0.0),
 (674, 0.0),
 (675, 0.0),
 (676, 0.0),
 (677, 0.0),
 (678, 0.0),
 (679, 0.0),
 (680, 0.0),
 (681, 0.0),

In [184]:
Tmovies_1.iloc[0].overview

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [187]:
Tmovies_1.iloc[2915].overview

'Set in Brazil, three kids who make a discovery in a garbage dump soon find themselves running from the cops and trying to right a terrible wrong.'